name: Build iOS XCFramework

on:
  workflow_dispatch: # Manual trigger
  push:
    branches: [master]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: ⚙️ Build iOS Simulator Frameworks Only
        run: |
         ./gradlew :composeApp:linkDebugFrameworkIosX64 --stacktrace --info
         ./gradlew :composeApp:linkDebugFrameworkIosSimulatorArm64 --stacktrace --info

      - name: 🧱 Assemble XCFramework Simulator Only
        run: ./gradlew :composeApp:assembleXCFramework --no-configuration-cache --stacktrace --info

      - name: Debug
        run: ls -la

      - name: Debug
        run: ls -la composeApp


