name: Build iOS XCFramework

on:
  workflow_dispatch: # Manual trigger
  push:
    branches: [master]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: List root directory files
        run: ls -la

      - name: List subdirectories recursively
        run: find . -type d

