name: Build iOS XCFramework

on:
  workflow_dispatch: # Manual trigger
  push:
    branches: [master]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: ⚙️ Build iOS Simulator Frameworks Only
        working-directory: ./composeApp
        run: |
          ./gradlew :composeApp:linkDebugFrameworkIosX64 --stacktrace --info
          ./gradlew :composeApp:linkDebugFrameworkIosSimulatorArm64 --stacktrace --info

      - name: 🧱 Assemble XCFramework Simulator Only
        working-directory: ./composeApp
        run: ./gradlew :composeApp:assembleXCFramework --no-configuration-cache --stacktrace --info

